			</table>
			<br>
			<?=$vote_submit?>
		</form>
								</TD>
                    </TR>
                  </TABLE>
								</TD>
              </TR>
            </TABLE></TD>
        </TR>
      </TABLE>