<?
$self_design_top .= "
<body>
<!--Top 로고와 작은메뉴들--><div id='Layer1' style='position:absolute; left:220px; top:155px; width:130; height:150; z-index:1; visibility: hidden;'>
  <table width='130' border='1' cellpadding='0' cellspacing='0' bordercolor='#CCCCCC' >
    <tr>
      <td bgcolor='#FFFFFF' style='filter:alpha(opacity=80)'><table width='120' border='0' align='center' cellpadding='0' cellspacing='0'>
        <tr>
          <td height='25'><span class='style2'> <a href='product_list.htm'>트렉스타</a> </span></td>
        </tr>
        <tr>
          <td><img src='../images/template6/image/sub_category_line.gif' width='120' height='1'></td>
        </tr>
        <tr>
          <td height='25'><span class='style2'>레저타임</span></td>
        </tr>
        <tr>
          <td><img src='../images/template6/image/sub_category_line.gif' width='120' height='1'></td>
        </tr>
        <tr>
          <td height='25'><span class='style2'> 하이텍</span></td>
        </tr>
        <tr>
          <td><img src='../images/template6/image/sub_category_line.gif' width='120' height='1'></td>
        </tr>
        <tr>
          <td height='25'><span class='style2'>오클리</span></td>
        </tr>
        <tr>
          <td><img src='../images/template6/image/sub_category_line.gif' width='120' height='1'></td>
        </tr>
        <tr>
          <td height='25'><span class='style2'> K2</span></td>
        </tr>
        <tr>
          <td><img src='../images/template6/image/sub_category_line.gif' width='120' height='1'></td>
        </tr>
        <tr>
          <td height='25'><span class='style2'> E3(파랑색-스케이트)</span></td>
        </tr>
        <tr>
          <td><img src='../images/template6/image/sub_category_line.gif' width='120' height='1'></td>
        </tr>
        <tr>
          <td height='25'><span class='style2'> E3(초록 - 안전화)</span></td>
        </tr>
      </table></td>
    </tr>
  </table>
</div>
<table width='990' border='0' cellspacing='0' cellpadding='0'>
  <tr>
    <td width='30'>&nbsp;</td>
    <td width='220'><a href='../main/index.php?mart_id=$mart_id'><img src='../images/template6/image/top/logo.gif' width='220' height='50' border='0'  ></a></td>
    <td align='right' valign='bottom'>
      <table border='0' cellspacing='0' cellpadding='0'>
        <tr>
          <td>
          <a href='../member/article.php?mart_id=$mart_id'>
          <img src='../images/template6/image/top/icon_1.gif' width='50' height='30' border='0'></a></td>
          <td><img src='../images/template6/image/top/icon_line.gif' width='6' height='30'></td>
          <td>
          <a href='../mypage/mypage1.php?mart_id=$mart_id'>
          <img src='../images/template6/image/top/icon_2.gif' width='50' height='30' border='0'></a></td>
          <td><img src='../images/template6/image/top/icon_line.gif' width='6' height='30'></td>
          <td>
          <a href='../mypage/mypage.php?mart_id=$mart_id'>
          <img src='../images/template6/image/top/icon_3.gif' width='60' height='30' border='0'></a></td>
          <td><img src='../images/template6/image/top/icon_line.gif' width='6' height='30'></td>
          <td>
          <a href='../cart/cart_view.php?mart_id=$mart_id'>
          <img src='../images/template6/image/top/icon_4.gif' width='50' height='30' border='0'></a></td>
          <td><img src='../images/template6/image/top/icon_line.gif' width='6' height='30'></td>
          <td>
          <a href='../stat/order.php?mart_id=$mart_id'>
          <img src='../images/template6/image/top/icon_5.gif' width='70' height='30' border='0'></a></td>
          <td><img src='../images/template6/image/top/icon_line.gif' width='6' height='30'></td>
          <td><img src='../images/template6/image/top/icon_6.gif' width='50' height='30' border='0'></td>
          <td><img src='../images/template6/image/top/icon_line.gif' width='6' height='30'></td>
          <td><img src='../images/template6/image/top/icon_7.gif' width='50' height='30' border='0'></td>
          <td><img src='../images/template6/image/top/icon_line.gif' width='6' height='30'></td>
          <td>
          <a href='../board/board_list.php?mart_id=$mart_id&bbs_no=1'>
          <img src='../images/template6/image/top/icon_8.gif' width='55' height='30' border='0'></a></td>
        </tr>
    </table></td>
  </tr>
</table>
<!--Top 로고와 작은메뉴들 끝-->
<!--Top 큰메뉴들-->
<table width='100%' border='0' cellspacing='0' cellpadding='0'>
  <tr>
    <td width='30' background='../images/template6/image/top/menu_bg.gif'>&nbsp;</td>
    <td width='110'><a href='javascript:bookmark()'><img src='../images/template6/image/top/add_favorites.gif' width='110' height='30' border='0'></a></td>
    <td width='120'><a href='brand.htm'><img src='../images/template6/image/top/view_brand.gif' width='120' height='30' border='0'></a></td>
    <td width='250' background='../images/template6/image/top/menu_bg2.gif'>&nbsp;</td>
    <td width='90' background='../images/template6/image/top/menu_1.gif'><object classid='clsid:D27CDB6E-AE6D-11cf-96B8-444553540000' codebase='http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0' width='90' height='30'>
        <param name='movie' value='../images/template6/flash/menuicon_1.swf'>
        <param name='quality' value='high'>
        <param name='wmode' value='transparent'>
        <embed src='../images/template6/flash/menuicon_1.swf' width='90' height='30' quality='high' pluginspage='http://www.macromedia.com/go/getflashplayer' type='application/x-shockwave-flash' wmode='transparent'></embed>
    </object></td>
    <td width='70'><img src='../images/template6/image/top/menu_2.gif' width='70' height='30'></td>
    <td width='100'><img src='../images/template6/image/top/menu_3.gif' width='100' height='30'></td>
    <td width='70'><img src='../images/template6/image/top/menu_4.gif' width='70' height='30'></td>
    <td width='70'><img src='../images/template6/image/top/menu_5.gif' width='70' height='30'></td>
    <td width='80' background='../images/template6/image/top/menu_6.gif'><object classid='clsid:D27CDB6E-AE6D-11cf-96B8-444553540000' codebase='http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0' width='80' height='30'>
        <param name='movie' value='../images/template6/flash/menuicon_3.swf'>
        <param name='quality' value='high'>
        <param name='wmode' value='transparent'>
        <embed src='../images/template6/flash/menuicon_3.swf' width='80' height='30' quality='high' pluginspage='http://www.macromedia.com/go/getflashplayer' type='application/x-shockwave-flash' wmode='transparent'></embed>
    </object></td>
    <td background='../images/template6/image/top/menu_bg.gif' >&nbsp;</td>
  </tr>
</table>
";
?>