<?
$self_design_intro .= ("
<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=ks_c_5601-1987'>
<title>New Page 1</title>
<meta name='GENERATOR' content='Microsoft FrontPage 3.0'>
</head>
<body topmargin='0' leftmargin='0'>
<table border='0' width='100%' height='100%' cellspacing='0' cellpadding='0'>
<tr>
    <td width='100%'><p align='center'>
    	<img src='../images/Image15.gif' width='341' height='127'><br>
    	<br>
    	<br>
    	<span class='zz'><strong>
    	<input class='bb' onclick=\"window.location.href='index.php?mart_id=$mart_id'\" style='BACKGROUND-COLOR: white; BORDER-BOTTOM: #7b7d7b 1px solid; BORDER-LEFT: #7b7d7b 1px solid; BORDER-RIGHT: #7b7d7b 1px solid; BORDER-TOP: #7b7d7b 1px solid; COLOR: #7b7d7b; HEIGHT: 18px' type='button' value='SKIP'></strong></span></td>
</tr>
</table>
</body>
</html>
");
?>