<?
$self_design_joinmail .= "
<html>

<head>
<meta http-equiv='Content-Type' content='text/html; charset=euc-kr'>
<title>회원가입 확인메일</title>
<style type='text/css'>
<!--
.aa {  font-size: 9pt; line-height: 12pt; color: #000000}
.bb {  line-height: 13pt; font-size: 9pt; color: #6B6B6B}
.ff { font-size: 8pt; color: #6B6B6B}
.cc {  font-size: 9pt; color: #FF9418}
.dd {  font-size: 9pt; color: #ffffff}
.ee {  font-size: 9pt; color: #2F7C99}
input { BORDER: #acacac 1px solid; HEIGHT: 18px; BACKGROUND-COLOR: #eeeeee}

A            {font-size: 9pt;line-height: 12pt;text-decoration: none;color: #000000 }
 A:hover      {text-decoration: none;  }  -->
</style>
</head>

<body>

<table border='0' width='670' cellpadding='3'>
  <tr>
    <td width='638' bgColor='#FFFFFF'><table border='5' width='100%' bordercolor='#E0E0E0'
    cellspacing='0'>
      <tr>
        <td width='100%'><table border='0' width='100%' cellspacing='0' cellpadding='0'>
          <tr>
            <td width='100%' bgcolor='#6489C4' height='30'><p align='right'>&nbsp; <span class='dd'>회원가입 
            확인메일&nbsp;&nbsp; </span></td>
          </tr>
          <tr>
            <td width='100%' bgcolor='#F1F1F1' height='1'></td>
          </tr>
          <tr>
            <td width='100%' bgcolor='#FFFFFF' height='10'></td>
          </tr>
          <tr>
            <td width='100%' bgcolor='#FFFFFF' height='20'><p align='center'>&nbsp;
            <img src='http://211.174.51.11/autocart/market/images/top1.gif'
            width='380' height='57' alt='top1.gif (3325 bytes)'></td>
          </tr>
          <tr>
            <td width='100%' bgcolor='#FFFFFF' height='20'><div align='center'><center><table
            border='0' width='90%' bgcolor='#EBEBEB' cellspacing='0' cellpadding='0'>
              <tr>
                <td width='100%' bgcolor='#DBDBDB'></td>
              </tr>
            </table>
            </center></div></td>
          </tr>
          <tr>
            <td width='100%' bgcolor='#ffffff' height='62'><div align='center'><center><table
            border='0' width='90%' cellspacing='0' cellpadding='0'>
              <tr>
                <td width='100%' height='10'><span class='aa'></span></td>
              </tr>
              <tr>
                <td width='100%'><span class='aa'>안녕하세요!&nbsp; [name]고객님<br>
                <br>
                저희 [shopname]쇼핑몰의 한가족이 되셨습니다.^*^<br>
                <br>
                앞으로 저희는 [name]님께 안전하고 우수한 서비스를 드리기 위해 
                최선을 다할 것을 약속드립니다. <br>
                다시 한번 회원으로 가입해주심을 감사드립니다.<br>
                <br>
                언제나 [name]님 곁에서 함께하며 행복을 드리는 [shopname]쇼핑몰이 되기 위해 
                열심히 뛰겠습니다. <br>
                계속 지켜봐 주세요.<br>
                <br>
                ☞ 회원님 아이디 : </span><span class='ee'><strong>[id]</strong></span><span
                class='aa'> / ☞ 패스워드 :</span><strong><span class='cc'> </span><span class='ee'>[password]</span></strong></td>
              </tr>
              <tr>
                <td width='100%' height='10'></td>
              </tr>
              <tr>
                <td width='100%' height='10'></td>
              </tr>
            </table>
            </center></div></td>
          </tr>
        </table>
        </td>
      </tr>
    </table>
    </td>
  </tr>
</table>

<table border='0' width='678'>
  <tr>
    <td width='638' bgColor='#FFFFFF'><table border='5' width='100%' bordercolor='#E0E0E0'
    cellspacing='0'>
      <tr>
        <td width='100%' height='40'><p align='center'><span class='ee'><strong>[shopname]쇼핑몰 
        고객센터</strong> : 전화) [tel], email : [email] </span></td>
      </tr>
    </table>
    </td>
  </tr>
  <tr>
    <td width='100%'><span class='aa'><br>
    </span></td>
  </tr>
</table>
</body>
</html>
";
?>