<?
$self_design_left .= "
<td width='160' valign='top'><table width='140' border='0' cellspacing='0' cellpadding='0'>
  <tr>
    <td><a href='../product/product_list.php?mart_id=$mart_id&category_num=10'><img src='../images/template6/image/main/category_1.gif' width='140' height='25' border='0' onMouseOver=\"MM_showHideLayers('Layer1','','show')\"></a></td>
  </tr>
  <tr>
    <td><a href='../product/product_list.php?mart_id=$mart_id&category_num=9'><img src='../images/template6/image/main/category_2.gif' width='140' height='25' border='0' onMouseOver=\"MM_showHideLayers('Layer1','','hide')\"></a></td>
  </tr>
  <tr>
    <td><a href='../product/product_list.php?mart_id=$mart_id&category_num=8'><img src='../images/template6/image/main/category_3.gif' width='140' height='25' border='0'></a></td>
  </tr>
  <tr>
    <td><a href='../product/product_list.php?mart_id=$mart_id&category_num=7'><img src='../images/template6/image/main/category_4.gif' width='140' height='25' border='0'></a></td>
  </tr>
  <tr>
    <td><a href='../product/product_list.php?mart_id=$mart_id&category_num=6'><img src='../images/template6/image/main/category_5.gif' width='140' height='25' border='0'></a></td>
  </tr>
  <tr>
    <td><a href='../product/product_list.php?mart_id=$mart_id&category_num=5'><img src='../images/template6/image/main/category_6.gif' width='140' height='25' border='0'></a></td>
  </tr>
  <tr>
    <td><a href='../product/product_list.php?mart_id=$mart_id&category_num=4'><img src='../images/template6/image/main/category_7.gif' width='140' height='25' border='0'></a></td>
  </tr>
  <tr>
    <td><a href='../product/product_list.php?mart_id=$mart_id&category_num=3'><img src='../images/template6/image/main/category_8.gif' width='140' height='25' border='0'></a></td>
  </tr>
  <tr>
    <td><a href='../product/product_list.php?mart_id=$mart_id&category_num=2'><img src='../images/template6/image/main/category_9.gif' width='140' height='25' border='0'></a></td>
  </tr>
  <tr>
    <td><a href='../product/product_list.php?mart_id=$mart_id&category_num=1'><img src='../images/template6/image/main/category_10.gif' width='140' height='25' border='0'></a></td>
  </tr>
</table></td>
";
?>    